// Generated by https://quicktype.io

export interface PaginatedUsers {
  page:        number;
  per_page:    number;
  total:       number;
  total_pages: number;
  data:        User[];
}

export interface User {
  id:         number;
  email:      string;
  first_name: string;
  last_name:  string;
  avatar:     string;
}
